---
# tasks file for docker-install
- name: Grab the Docker Install Script
  get_url:
    url: https://get.docker.com
    dest: /tmp/get-docker.sh
    mode: 0755

- name: Verify Docker Command
  shell: command -v docker >/dev/null 2>&1
  ignore_errors: true
  register: docker_cli_exists

- debug: msg="{{ docker_cli_exists.rc }}"

- name: Exec Docker Script
  shell: |
    echo "Docker installing" &&
    sh /tmp/get-docker.sh
  when: docker_cli_exists.rc != 0
