- name: Install & Configure NGINX
  hosts: all
  become: true
  tasks:
    - name: Install NGINX
      apt:
        name: nginx
        update_cache: yes
        state: present
    - name: Create HTML File
      copy:
        dest: /var/www/html/index.html
        content: |
          <h1>Try Infrastructure as Code</h1>
          <p>With Ansible</p>