- name: Config Webapps Play
  hosts: webapps
  roles:
    - docker-install
    # - compose-app
  # tasks:
  tasks:
    - name: CFE Nginx App
      include_role:
        name: compose-app
        vars_from: cfe-nginx.yml
    - name: Docker Stop Compose
      shell:
        cmd: docker compose -f compose.prod.yaml down --rmi all --remove-orphans
        chdir: /var/www/webapp/
        executable: /bin/bash